apiVersion: lava.linaro.org/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: lava-controller
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # TODO(user): Add fields here
